#!/bin/sh
set -eu

BOOT_FILE="${BOOT_FILE:-/boot/cmdline.txt}"
FLAG="${FLAG:-/boot/rollback.flag}"

/usr/local/sbin/sd-restore.sh

CMD="$(tr '\n' ' ' < "$BOOT_FILE")"
case " $CMD " in
  *" root="*) : ;;
  *) echo "no root= in $BOOT_FILE" >&2; exit 1;;
esac

rm -f "$FLAG"
sync
reboot
